config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :posts
  resources :tests do
    resources :answers
    resources :stars
  end

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # has_attached_file :document
  # validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  belongs_to :user
  validates :content, presence: true

end

app/models/star.rb
class Star < ApplicationRecord
  validates :user, uniqueness: { scope: :test_id }
  belongs_to :user
  belongs_to :test
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :stars
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :stars
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
    @tests = Test.all
    @users = User.all

  end

  def new

    @test = Test.find(params[:test_id])
    @answer = Answer.new
    @question = @test.question
  end

  def create
    # @test =  Test.find(params[:test_id])
    # @answer = Answer.new(test: @test, user: current_user)
    @answer = Answer.new(answer_params)
    @answer.user = current_user
    @answer.test = Test.find(params[:test_id])
    @answer.save
    if @answer.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])

    if @answer.update(answer_params)
      redirect_to @answer, notice: "#{@answer.name} foi editado."
      @answer.save
    else
      render :edit
    end
  end

  def show
    @test = Test.find(params[:id])
    @answers = Answer.find(params[:id])
    @answer = @answers.test
  end

  def destroy
    @user = User.find(params[:id])
    @test = Test.find(params[:test_id])
    @answer = Answer.find_by(test: @test, user: @user)
    @answer.destroy
    redirect_to test_answers_path, notice: "A resposta foi excluída!"
  end

  private

  def answer_params
    params.require(:answer).permit(:answer1, :answer2, :answer3, :answer4)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name teacher president photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name teacher president photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @post = Post.last
    @test = Test.all
    @answers = Answer.all
    @user = current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    # @posts = @post.posts.order(created_at: :desc)
    @new_post = Post.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
    @post = Post.find(params[:post_id])
  end

  private

  def post_params
    params.require(:post).permit(:content, :memorize, :user_id, :post_id, files: [])
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  def show
    @users = user.all
  end

  def index
    @users = User.all

  end

  def new
    @star = Star.new
    @user = User.find(params[:user_id])
    @user.score += 1

    redirect_to test_stars_path
  end

  def create
    @test = Test.find(params[:test_id])

    # @star = Star.new(user: )

    if !@star.save
      redirect_to test_stars_path
    end
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @tests = Test.all
    @answers = Answer.all
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)
    @test.save
    if @test.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @test = Test.find(params[:id])
  end

  def update
    @test = Test.find(params[:id])

    if @test.update(test_params)
      redirect_to @test, notice: "O questionário foi editado."
      @test.save
    else
      render :edit
    end
  end

  def show
    @test = Test.find(params[:id])
    @answers = Answer.all
  end

  def destroy
    @test = Test.find(params[:id])
    @test.destroy
    redirect_to root_path, notice: "O Questionário #{@test.id} foi cancelado!"
  end

  private

  def test_params
    params.require(:test).permit(:question1, :question2, :question3, :question4, :private)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @score = @user.score
    @score = 0
  end

  def user_params
    params.require(:user).permit(:photo)
  end

  def index
    @users = User.all
    @tests = Test.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/index.html.erb
<div class="container">
  <div class="row">
    <% @answers.each do |answer| %>
      <div class="col-12 col-md-6 col-lg-4 p-2">
        <% if answer.user.teacher %>
          <div class="teacher-answer">
            <%= "Semana #{answer.test.id} - Respostas" %>
            <%= link_to test_answer_path(answer.test_id, answer.user_id), method: :delete do %>
              <i class="fas fa-backspace"></i>
            <% end %>
            <p><b><%= answer.test.question1 %></b> <%= answer.answer1 %></p>
            <p><b><%= answer.test.question2 %></b> <%= answer.answer2 %></p>
            <p><b><%= answer.test.question3 %></b> <%= answer.answer3 %></p>
            <p><b><%= answer.test.question4 %></b> <%= answer.answer4 %></p>
          </div>
        <% else %>
          <div class="student-answer">
            <%= cl_image_tag answer.user.photo.key, gravity: :face, crop: :thumb, class: "avatar" %>
            <%= answer.user.first_name.titleize + " " + answer.user.last_name.titleize + " " + "- Semana #{answer.test.id}" %>
            <%= link_to test_answer_path(answer.test_id, answer.user_id), method: :delete do %>
              <i class="fas fa-backspace"></i>
            <% end %>
            <p><b><%= answer.test.question1 %></b> <%= answer.answer1 %></p>
            <p><b><%= answer.test.question2 %></b> <%= answer.answer2 %></p>
            <p><b><%= answer.test.question3 %></b> <%= answer.answer3 %></p>
            <p><b><%= answer.test.question4 %></b> <%= answer.answer4 %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  
</div>

app/views/answers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-4">
      <% if current_user.teacher || @test.private == true %>
        <%= simple_form_for [@test, @answer] do |f| %>
          <% @question.each do |q| %>
            <h4><%= q %></h4>
            <%= f.input :answer, label: false, value: "resposta" %>

          <% end %>
          <%= f.submit "Enviar", class:"btn btn-primary" %>
        <% end %>
      <% else %>
        <h4>Você não tem autorização para acessar essa página</h4>
      <% end %>
      <%= render 'shared/footer' %>
    </div>
  </div>
</div>

app/views/answers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-4">
      <% @answers.each do |a| %>
        <h5>Semana <%= a.test.id %></h5>
        <%= cl_image_tag a.user.photo.key, gravity: :face, crop: :thumb, width: 40, height: 40, class: "avatar" %>
        <%= a.user.first_name.titleize + " " + a.user.last_name.titleize %>
        <p><b><%= a.test.question1 %></b> <%= a.answer1 %></p>
        <p><b><%= a.test.question2 %></b> <%= a.answer2 %></p>
        <p><b><%= a.test.question3 %></b> <%= a.answer3 %></p>
        <p><b><%= a.test.question4 %></b> <%= a.answer4 %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Provinha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>!-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' unless current_page?(new_user_password_path) || current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
    <%= render 'shared/flashes' unless current_page?(new_user_registration_path) %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container center-container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <div class="d-flex">
        <h4><%= "Conteudo da semana" %></h4>
        <% if current_user.teacher%>
          <%= link_to new_post_path do  %>
            <i class="fas fa-plus-circle p-1"></i>
          <% end %>
        <% end %>
      </div>
      <%= cl_image_tag Post.last.user.photo.key, class: "avatar",
        transformation: [ {gravity: :face, height: 400, width: 400, crop: :fill},
        {radius: :max},
        {width: 200, crop: :scale} ] if Post.last.present? %>
      <%= Post.last.content if Post.last.present? %>
      <p><%= link_to "Memorizar", post_path(Post.last) if Post.last.present? %></p>
      <table>
        <th></th>
        <th>Semana</th>
        <th>Opções</th>
        <% i = 0 %>
        <% if @test.present? %>
          <% @test.each do |t| %>
            <tr>
              <% if t.private == true || current_user.teacher  %>
                <td>
                  <% if t.private %>
                    <i class="fas fa-unlock-alt"></i>
                  <% else %>
                    <i class="fas fa-lock"></i>
                  <% end %>
                </td>
                <td><%= link_to "Semana #{t.id}", test_path(t) %></td>
                <td>
                  <% if current_user.teacher %>
                    <%= link_to edit_test_path(t) do %>
                      <i class="fas fa-edit"></i>
                    <% end %>
                    <%= link_to test_path(t), method: :delete do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
                    <%= link_to test_answers_path(t) do %>
                      <i class="fas fa-check-square"></i>
                    <% end %>
                  <% else %>
                    <%= link_to "Entrar", test_path(t), class: "btn btn-primary" %>
                    <% if current_user.president  %>
                      <%= link_to test_stars_path(t) do %>
                        <i class="fas fa-star star-hover"></i>
                      <% end %>
                    <% end %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </table>
      <% if current_user.teacher %>
        <%= link_to new_test_path do %>
          <i class="fas fa-plus-circle fa-2x p-2"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-4">
      <%= simple_form_for @post do |f| %>
        <%= f.input :content, label: false, placeholder: 'Informações', input_html: {class: 'ps-3 form-control'} %>
        <%= f.input :memorize, label: false, placeholder: "Memorizar", input_html: {class: 'ps-3 form-control'} %>
        <%#= f.input :files, label: false, as: :file, input_html: { multiple: true, class: "d-none" } %>
        <%= f.submit 'Enviar', class: 'btn btn-primary' %>
      <% end %>


      <%= render 'shared/footer' %>

    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <% memorize = @post.memorize.split(" ") %>
      <% memorize.each do |x| %>
        <% x[rand(0..2)..rand(3..5)] = "___" if x.length > 3 %>
        <% x[rand(1..2)..rand(1..3)] = "_" if x.length > 2 && x.length < 4 %>
        <%= x %>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bottom-icons">
  <%= link_to :back do %>
    <i class="fas fa-arrow-circle-left fa-3x"></i>
  <% end %>
</footer>

app/views/shared/_icon.html.erb
<% if current_user.teacher %>
  <i class="fas fa-user-tie"></i>
<% elsif current_user.president %>
  <i class="fas fa-crown"></i>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container d-flex">
  <% if user_signed_in? %>
    <div class="hide-mobile">
      <% if current_user.photo.key.present? %>
        <%= cl_image_tag current_user.photo.key, class: "avatar-large dropdown-toggle m-2",
        transformation: [ {gravity: :face, height: 400, width: 400, crop: :fill},
        {radius: :max},
        {width: 200, crop: :scale} ] %>
        <%= render 'shared/icon' %>
      <% end %>
    </div>
    <div class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <% if current_user.photo.key.present? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar-large dropdown-toggle m-2", id: "navbarDropdown",
          data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false,
          transformation: [ {gravity: :face, height: 400, width: 400, crop: :fill},
            {radius: :max},
            {width: 200, crop: :scale} ] %>
            <%# current_user.score = 35 %>
            <%= render 'shared/icon' %>
          <% end %>
        </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <% unless current_user.teacher %>
          <p class="dropdown-item m-0">Pontos: <%= current_user.score %></p>
        <% end %>
        <!-- Use a classe "navbar-nav" para agrupar os links da barra de navegação -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <!-- Link para a página inicial -->
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <!-- Link para o perfil do usuário -->
          <li class="nav-item">
            <%= link_to "Perfil", edit_user_registration_path, class: "nav-link" %>
          </li>
          <!-- Link para sair da sessão -->
          <li class="nav-item">
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link", data: { confirm: "Deseja sair?" } %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>
      </div>
    </div>
  <% end %>
</div>

app/views/stars/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <div class="d-flex flex-wrap justify-content-center">
        <% if current_user.teacher || current_user.president %>
          <% @users.each do |u| %>
            <% unless u.teacher %>
              <div class="d-flex flex-column m-2 mb-0 align-items-center">
                <%= cl_image_tag u.photo.key, class: "avatar-large align-self-center",
                transformation: [ {gravity: :face, height: 400, width: 400, crop: :fill},
                {radius: :max},
                {width: 200, crop: :scale} ] %>
                <%= u.first_name.titleize %>
                <%= link_to new_test_star_path(u), method: :get do%>
                  <i class="fas fa-star star-index"></i>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
    </div>
  </div>
</div>